### ISSUE TITLE
李某人的修行路 | 友链

### ISSUE THREAD

**Issue by lypzzz** [lypzzz/lypzzz.github.io#10]
https://lypzz.com/friends/ 

 个人博客，致力于Java，Web，编程记录。

**Comment by lypzzz** [comment]
测试1

**Comment by lypzzz** [comment]
测试2

**Comment by lypzzz** [comment]
测试3

**Comment by lypzzz** [comment]
测试4

**Comment by lypzzz** [comment]
测试5

**Comment by lypzzz** [comment]
测试6

**Comment by lypzzz** [comment]
测试7

**Comment by lypzzz** [comment]
测试8

**Comment by lypzzz** [comment]
测试9

**Comment by lypzzz** [comment]
测试10

**Comment by lypzzz** [comment]
测试11

**Comment by lypzzz** [comment]
测试12

**Comment by lypzzz** [comment]
```yaml
name: '某个大帅哔的Blog'
url: 'https://lypzz.com/'
logo: 'https://lypzz.com/img/favicon.ico'
desc: '为之于未有，治之于未乱。'
```
